version: "3.9"

services:
  user_service:
    build: ./user_service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      - PORT=${USER_SERVICE_PORT}
    volumes:
      - user_data:/app/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${USER_SERVICE_PORT}/users/1"]
      interval: 10s
      timeout: 3s
      retries: 3

  order_service:
    build: ./order_service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    depends_on:
      - user_service
    environment:
      - USER_SERVICE_URL=http://user_service:${USER_SERVICE_PORT}
      - PORT=${ORDER_SERVICE_PORT}
    networks:
      - app-net

volumes:
  user_data:

networks:
  app-net:
    driver: bridge
